spring:
  profiles:
    active: dev
  datasource:
      data-username: root
      data-password: root1234
      url: jdbc:mysql://127.0.0.1:3306/test
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:

mybatis:
  type-aliases-package: com.inshare.user.entity
  mapper-locations: classpath:mapper/*.xml

mapper:
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

hello:
  msg: 这是自动配置测试内容

logging:
  level:
    com.inshare.user.mapper: trace
